### ISSUE TITLE
Missing IC2 crash although it is on the server

### ISSUE THREAD

**Issue by TheAirBlow** [ThePansmith/Enigmatica2ExpertUnofficial#9]
**Modpack version**
1.0.5

**Issue**
Compact Solar Arrays requires IC2 which is installed but isn't detected
![image](https://user-images.githubusercontent.com/68467762/227769584-be398b46-73a0-4a45-9219-0e3e0931cdd0.png)

**Logs**
```
[10:20:06] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod compactsolars (Compact Solar Arrays) requires [ic2@[2.8,)]
[10:20:06] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.MissingModsException: Mod compactsolars (Compact Solar Arrays) requires [ic2@[2.8,)]
        at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266) ~[Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[10:20:06] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/container/./crash-reports/crash-2023-03-26_10.20.06-server.txt
```

**Comment by TheAirBlow** [comment]
Maybe I somehow got it corrupted? Anyways, I have no idea, if it isn't reproducible that is the problem.
I've deleted that server from pterodactyl already as I realized I can't run the modpack on my laptop.
Server is fine though, 24 GB of RAM thanks to oracle
